# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(852, 760)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageicono = QtWidgets.QLabel(self.groupBox)
        self.imageicono.setText("")
        self.imageicono.setObjectName("imageicono")
        self.verticalLayout.addWidget(self.imageicono)
        self.drawmoduleandazimuthdistribution = QtWidgets.QRadioButton(self.groupBox)
        self.drawmoduleandazimuthdistribution.setChecked(True)
        self.drawmoduleandazimuthdistribution.setObjectName("drawmoduleandazimuthdistribution")
        self.verticalLayout.addWidget(self.drawmoduleandazimuthdistribution)
        self.drawdistribution = QtWidgets.QRadioButton(self.groupBox)
        self.drawdistribution.setObjectName("drawdistribution")
        self.verticalLayout.addWidget(self.drawdistribution)
        self.drawhistogram = QtWidgets.QRadioButton(self.groupBox)
        self.drawhistogram.setObjectName("drawhistogram")
        self.verticalLayout.addWidget(self.drawhistogram)
        self.drawPoints = QtWidgets.QRadioButton(self.groupBox)
        self.drawPoints.setObjectName("drawPoints")
        self.verticalLayout.addWidget(self.drawPoints)
        self.drawdensityMap = QtWidgets.QRadioButton(self.groupBox)
        self.drawdensityMap.setObjectName("drawdensityMap")
        self.verticalLayout.addWidget(self.drawdensityMap)
        self.drawqqplot = QtWidgets.QRadioButton(self.groupBox)
        self.drawqqplot.setObjectName("drawqqplot")
        self.verticalLayout.addWidget(self.drawqqplot)
        self.drawVectors = QtWidgets.QRadioButton(self.groupBox)
        self.drawVectors.setObjectName("drawVectors")
        self.verticalLayout.addWidget(self.drawVectors)
        self.modstats = QtWidgets.QRadioButton(self.groupBox)
        self.modstats.setObjectName("modstats")
        self.verticalLayout.addWidget(self.modstats)
        self.azimuthstats = QtWidgets.QRadioButton(self.groupBox)
        self.azimuthstats.setObjectName("azimuthstats")
        self.verticalLayout.addWidget(self.azimuthstats)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 7)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.type1 = QtWidgets.QRadioButton(self.splitter_3)
        self.type1.setObjectName("type1")
        self.type0 = QtWidgets.QRadioButton(self.splitter_3)
        self.type0.setChecked(True)
        self.type0.setObjectName("type0")
        self.type2 = QtWidgets.QRadioButton(self.splitter_3)
        self.type2.setObjectName("type2")
        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 4)
        self.calculate = QtWidgets.QPushButton(Form)
        self.calculate.setEnabled(False)
        self.calculate.setObjectName("calculate")
        self.gridLayout_2.addWidget(self.calculate, 1, 4, 1, 1)
        self.buttonload = QtWidgets.QPushButton(Form)
        self.buttonload.setObjectName("buttonload")
        self.gridLayout_2.addWidget(self.buttonload, 1, 5, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.Files = QtWidgets.QRadioButton(self.splitter_2)
        self.Files.setChecked(True)
        self.Files.setObjectName("Files")
        self.Map = QtWidgets.QRadioButton(self.splitter_2)
        self.Map.setObjectName("Map")
        self.labelpath = QtWidgets.QLabel(self.splitter_2)
        self.labelpath.setText("")
        self.labelpath.setObjectName("labelpath")
        self.gridLayout_2.addWidget(self.splitter_2, 1, 6, 2, 1)
        self.labelModules = QtWidgets.QLabel(Form)
        self.labelModules.setEnabled(False)
        self.labelModules.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelModules.setObjectName("labelModules")
        self.gridLayout_2.addWidget(self.labelModules, 2, 0, 1, 1)
        self.comboBoxModules = QtWidgets.QComboBox(Form)
        self.comboBoxModules.setObjectName("comboBoxModules")
        self.gridLayout_2.addWidget(self.comboBoxModules, 2, 1, 1, 1)
        self.labelAzimuths = QtWidgets.QLabel(Form)
        self.labelAzimuths.setEnabled(False)
        self.labelAzimuths.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAzimuths.setObjectName("labelAzimuths")
        self.gridLayout_2.addWidget(self.labelAzimuths, 2, 2, 1, 1)
        self.comboBoxAzimuths = QtWidgets.QComboBox(Form)
        self.comboBoxAzimuths.setObjectName("comboBoxAzimuths")
        self.gridLayout_2.addWidget(self.comboBoxAzimuths, 2, 3, 1, 1)
        self.savedata = QtWidgets.QPushButton(Form)
        self.savedata.setEnabled(False)
        self.savedata.setObjectName("savedata")
        self.gridLayout_2.addWidget(self.savedata, 2, 4, 1, 1)
        self.buttonmap = QtWidgets.QPushButton(Form)
        self.buttonmap.setEnabled(False)
        self.buttonmap.setObjectName("buttonmap")
        self.gridLayout_2.addWidget(self.buttonmap, 2, 5, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Circular Satistics Studio"))
        self.groupBox.setTitle(_translate("Form", "            Circular Statistics Studio"))
        self.drawmoduleandazimuthdistribution.setText(_translate("Form", "ModuleandAzimuthDistribution"))
        self.drawdistribution.setText(_translate("Form", "Distribution"))
        self.drawhistogram.setText(_translate("Form", "Histogram"))
        self.drawPoints.setText(_translate("Form", "Points"))
        self.drawdensityMap.setText(_translate("Form", "DensityMap"))
        self.drawqqplot.setText(_translate("Form", "QQplot"))
        self.drawVectors.setText(_translate("Form", "Vectors"))
        self.modstats.setText(_translate("Form", "Module stats"))
        self.azimuthstats.setText(_translate("Form", "Azimuths stats"))
        self.type1.setText(_translate("Form", "Incremental"))
        self.type0.setText(_translate("Form", "Cartesian"))
        self.type2.setText(_translate("Form", "Polar"))
        self.calculate.setText(_translate("Form", "Calculate"))
        self.buttonload.setText(_translate("Form", "Select file"))
        self.Files.setText(_translate("Form", "Files"))
        self.Map.setText(_translate("Form", "Map"))
        self.labelModules.setText(_translate("Form", "Modules"))
        self.labelAzimuths.setText(_translate("Form", "Azimuths"))
        self.savedata.setText(_translate("Form", "Save Data"))
        self.buttonmap.setText(_translate("Form", "Load Map"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

